#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
server:
  port: 9095
spring:
  datasource:
    username: sa
    password: root
    url: jdbc:h2:mem:rbac-spring-boot-test?createDatabaseIfNotExist=true
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  #JPA Hibernate
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

